### ISSUE TITLE
lib/fontmin-loader.jsについて

### ISSUE THREAD

**Issue by SnO2WMaN** [hakatashi/iwashi#3]
ここに書く内容であるか迷いましたが、他に報告できる場所がなかったのでIssueで投げるという形にさせていただきました。大変申し訳ございません。

この度、MITライセンスに基づき、lib/fontmin-loader.jsを当方でnpmパッケージ化いたしました。

https://github.com/SnO2WMaN/font-min-loader

https://www.npmjs.com/package/font-minify-loader

なにか問題があれば修正、削除いたします。

**Comment by hakatashi** [comment]
すみません、ずっとIssue見逃してました! 全く問題ありません。私のコードが役に立ったようで嬉しいです。ありがとうございます!!

**Comment by SnO2WMaN** [comment]
ありがとうございます。
